site_name: josh donnelly
theme:
  name: material
  palette:
    primary: blue grey
    accent: cyan
  color_mode: dark
  user_colod_mode_toggle: true
  highlightjs: true

  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Environments: environments.md
  - Infrastructure: infra.md
  - Security & Hardening: security.md
  - Kubernetes & App Deployments: applications.md
  - Security Monitoring: monitoring.md
  - Costs: costs.md
  - Dashboards: dashboard.md
  - About Me: aboutme.md

