site_name: josh donnelly
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - search.highlight
    - search.suggest
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/donnellyjdd

repo_url: https://github.com/donnellyj/joshdonnelly
nav:
  - Home: index.md
  - Environments: environments.md
  - Infrastructure: infra.md
  - Security & Hardening: security.md
  - Kubernetes & App Deployments: applications.md
  - Security Monitoring: monitoring.md
  - Costs: costs.md
  - Dashboards: dashboard.md
  - About Me: aboutme.md

